services:
  frontend-app:
    build:
      context: ./react_frontend/react-app
    volumes:
      - frontend_dist:/app/dist
  db:
    image: postgres:16
    container_name: postgres16_fonts
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -q -d $${DB_NAME} -U $${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_fonts
    restart: always
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - db

  app:
    build:
      context: ./django_backend
    restart: always
    volumes:
      - static-data:/vol/web/static
      - media-data:/vol/web/media
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DOCKER_PROJECT=1
  proxy:
    environment:
      - SERVER_NAME=fonts.unimatch.ru
      - LISTEN_PORT=80
    build:
      context: ./proxy
    restart: always
    depends_on:
      - app
      - frontend-app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static-data:/vol/static
      - media-data:/vol/media
      - frontend_dist:/usr/share/nginx/html:ro
      - letsencrypt:/etc/letsencrypt
      - certbot-webroot:/var/www/certbot

  certbot:
    image: certbot/certbot:latest
    volumes:
      - letsencrypt:/etc/letsencrypt
      - certbot-webroot:/var/www/certbot

volumes:
  pgdata:
  static-data:
  media-data:
  db-data:
  frontend_dist:
  certbot-webroot:
  letsencrypt:
